global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'django-app'
    static_configs:
      - targets: ['172.17.0.2:8000']  # Replace with your app's IP and metrics port.
