name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t my-django-ecommerce .

      - name: Run tests
        run: |
          docker run --rm my-django-ecommerce python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@192.168.0.227 'docker pull your-docker-image:latest && docker run -d -p 8000:8000 your-docker-image:latest'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

