name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t muhammadhamzaamin/my-django-ecommerce .
        docker push muhammadhamzaamin/my-django-ecommerce

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@192.168.0.227 <<EOF
          docker pull muhammadhamzaamin/my-django-ecommerce
          docker stop my-django-app || true
          docker rm my-django-app || true
          docker run -d --name my-django-app -p 8000:8000 muhammadhamzaamin/my-django-ecommerce
        EOF

